sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
script: npm run build
deploy:
  provider: heroku
  api_key:
    secure: pJjxmY8CkJa1Ibdhwk9lXYiraHnGBl+0TEzKmEnw6T+o15Ik2e7mbVxG/NQCIHz1aC1kiHvKJDlfPkVd9EK4ysUPnjiYlQGpD+p+jNI1HKSWaB+pXcRWtE0BzhL1svERZZccO/jecIV9lhu/lDeF3bOpu9Piz1g0hwm7jHHbbLHXNjdKzV8wX2pBmBl3KrGqbqRCgy3Blcki5Mk4Efm64TNxLWDS4x6y8wumru31EbJLDUYr8xYFsXBmPQU30S3hba96b1CA78xFBqcd5yZdj4cx0EfeQ31vtLFTuxGweGAuc5m7bgVdyPpDHgrTZG4FRLoTd6u+frnGkcsDdoW4knPfxWtA/r+Wmf6gPJxGbdCOvwhi1yjMV3W0Nb9deJJPJ01u5UwS2K3FrrUmkFpP7QXZ1lUKup2nOiaJCIEE7j9e71yQEBNeFLQQVzGT7HyUGIzyika4/c+RCGRQwBdf7RyGv3mWsF7lEbwpK9SMOzB+kn59HrPGb9LUIKlK2jkNFEZQcZktTozvMjj3STnsq/zd6eQ70C4R8HZ+HlJdCT3Ai232OeBvWjLq9yWncSlzYWcqPD+3wB2LiJ4t5kSTcjBTF+83nYq4sWD4rBVCYwSZapHJ24KCMhGZ/qeuz8RxgS/4r1vLYH0SKriKYKz7158JpuJ8zxRUfjTXh0eLRSI=
  app: antokara-me
  on: master
